# find the total revenue generated by repeated customer and how much their contribution in total revenue of a business
create or replace table `august-mesh-488818-i9.ecommerce_analysing.customer_retention_revenue` as(
with user_orders as (
  select 
    user_id,
    count(order_id) as order_counts
    from `august-mesh-488818-i9.ecommerce_analysing.clear_revenue_table`
    group by user_id
)
select
  sum(r.revenue)as total_revenue,
  sum(
    case
      when u.order_counts>1 then r.revenue
    end
  ) as revenue_from_rc,
  round(
    safe_divide(
      sum(case when u.order_counts>1 then r.revenue end
  ) ,sum(r.revenue)),2) as rc_revenue_rate
  from `august-mesh-488818-i9.ecommerce_analysing.clear_revenue_table` r
  join user_orders u
  on u.user_id= r.user_id
);
